//! The essays themselves, authored in Rust. One function per essay returning the
//! contents of `<article class="essay">`. Prose is transcribed verbatim from the
//! original pages; a build check (see justfile / verify step) diffs the rendered
//! output against the originals to guarantee fidelity.

use maud::{html, Markup};

pub struct Essay {
    pub slug: &'static str,
    pub title: &'static str,
    pub body: Markup,
}

pub fn all() -> Vec<Essay> {
    vec![
        harness_engineering(),
        ai_governance_framework(),
        dimensional_classification(),
        hootl_rsi(),
    ]
}

fn harness_engineering() -> Essay {
    Essay {
        slug: "harness-engineering",
        title: "The Harness Is the Frontier",
        body: html! {
            h1 { "The Harness Is the Frontier. Harness Engineering Is What Matters Most in the Near Term." }
            img src="images/harness-engineering.jpg" alt="The Harness Is the Frontier" class="essay-hero";
            p class="post-meta" { "Published on July 4, 2026" }
            p { em { "Frontier models are converging. The scaffolding around them isn't. The steepest gradient available right now runs through the harness, and almost nobody is climbing it systematically." } }
            p { "Everyone is waiting for the next model. The next release, the next benchmark chart with a new bar on the right. And the models do keep getting better. But if you actually work with agents every day, you notice something that the release-cycle framing misses entirely: the difference between two agent products running the " em { "same model" } " is often larger than the difference between two model generations running the same product." }
            p { "Give the same frontier model to two different agent harnesses and you get wildly different outcomes. One flails, reads the wrong files, forgets what it was doing, and declares victory on broken code. The other decomposes the task, verifies its own work, and lands the change. Same weights. Same intelligence, if you want to call it that. The delta is everything wrapped around the model: the system prompt, the tools and how they're described, the skills, the subagents, the memory, the context management, the feedback loops. The harness." }
            p { "In the near term, I think harness engineering is where the most capability per unit of effort will come from. Not pre-training, not post-training. The harness." }
            h2 { "What a Harness Actually Is" }
            p { "The model is an engine. The harness is everything that decides what the engine sees and what happens to what it produces. Concretely, that means the system prompt that frames the agent's behavior. The tool registry and, critically, the tool " em { "descriptions" } ", which are load-bearing prose that most teams have never revised since the day they were written. The skills and reference documents the agent can pull in. The subagents it can delegate to. The long-term memory it accumulates. The compaction strategy when context runs out. The verification loops that decide whether work is done." }
            p { "None of this is weights. All of it is text and code sitting in files. That's why it matters: it's the part of the system anyone can change, today, without a GPU cluster." }
            h2 { "The Paper That Made This Rigorous" }
            p { "In April, Jiahang Lin and collaborators released " a href="https://arxiv.org/abs/2604.25850" { "Agentic Harness Engineering: Observability-Driven Automatic Evolution of Coding-Agent Harnesses" } ". It turned harness engineering from a folk craft into something you can measure, and I think it's one of the most important papers of the year." }
            p { "The setup: hold the base model completely fixed. Externalize the harness into seven file-level components (system prompt, tool descriptions, tool implementations, middleware, skills, subagents, long-term memory), each git-tracked so every edit is auditable and revertible. Then run an " em { "evaluate → analyze → improve" } " loop where agents improve the harness itself. A debugger agent distills roughly ten million tokens of raw execution traces per iteration into layered, sourced reports. An evolve agent reads the evidence, proposes edits with a predicted impact, and commits them. The next iteration's results falsify or confirm the prediction. Regressions roll back." }
            p { "The results are the point. Over ten iterations, with the model frozen, the evolved harness lifted Terminal-Bench 2 pass@1 from 69.7% to 77.0% on GPT-5.4, past the hand-written Codex harness at 71.9%. An automated loop editing prompt files and tool descriptions beat the harness a frontier lab wrote by hand for its own model. A later run on GPT-5.5 hit 84.7%, third place on the Terminal-Bench 2.0 leaderboard." }
            p { "The part I keep coming back to is that the frozen harness " em { "transferred" } ". Without re-evolution it improved performance on SWE-bench-verified and on four other base models. The evolved components weren't overfitting to a benchmark. They were encoding general engineering experience, the kind of operational judgment senior engineers accumulate, written down as files a model can use." }
            p { "That transfer result is the empirical core of my argument. It means harness improvements are not model-specific tuning tricks that evaporate on the next release. They're durable capital. Every point of capability you bake into the harness survives the model swap underneath it and compounds with whatever the next model brings." }
            h2 { "Applying the Paradigm: Wizard" }
            p { a href="https://github.com/teddytennant/wizard" { "Wizard" } " is my sovereign coding agent: one Rust binary, any model, self-extending through audited and reversible steps. Its harness was already externalized by design: everything it learns lives as plain files under " code { "~/.wizard/" } ". That made it a natural evolve target." }
            p { "So I built a private AHE lab around it. Wizard exports its full harness bundle (system prompt, per-tool descriptions, skills, subagents), and the lab runs it against a Docker task set, has a meta-agent analyze the transcripts and rewrite the bundle, then re-measures. Each edit is a git commit carrying its evidence, root cause, fix, and predicted impact, in the paper's mold. Per-task verifiers score the rollouts; a flipped task falsifies the evolve agent's prediction and the regressed edit rolls back automatically. Bundles that win get human-reviewed and baked back into wizard as new compiled defaults, so the next round starts from an improved baseline rather than re-deriving the same lessons." }
            p { "The early experience matches the paper's findings in miniature. The highest-value edits are rarely glamorous. They're tool descriptions rewritten to say what the tool is actually for. Failure-mode notes added to a skill after the debugger traced three rollouts dying the same way. The loop finds the boring, load-bearing fixes that a human maintainer knows they should make and never gets around to." }
            h2 { "Applying the Paradigm: FUSION" }
            p { a href="https://github.com/teddytennant/FUSION" { "FUSION" } " is a different kind of agent system, a multi-model debate CLI where several frontier models answer the same query, critique each other over review rounds, and a synthesizer merges the result. There's no tool use to evolve there. But FUSION still has a harness, and it's almost entirely prose: the initial-generation prompt, the critique prompt, the synthesis prompt, the roster policy. Those prompts were written once, by me, on intuition." }
            p { "Prompts written on intuition are just the kind of artifact the AHE loop is built to improve. Run the debate over tasks with verifiable answers. Let a debugger agent read the transcripts and work out where a critique round added signal and where it just added agreement. Let an evolve agent rewrite the critique and synthesis prompts with predictions the next run can falsify. This work is earlier-stage than the wizard lab, but the loop carries over, because nothing about it depended on coding agents in particular. It needs an externalized harness, verifiable outcomes, and observability connecting the two." }
            h2 { "The Safe End of Recursive Self-Improvement" }
            p { "In February I wrote that " a href="hootl-rsi.html" { "full human-out-of-the-loop recursive self-improvement is becoming viable" } ", and predicted that 2026-2027 would bring narrow HOOTL RSI in constrained domains: automated optimization loops improving specific subsystems without human oversight. Harness evolution is that prediction arriving, and it's worth noticing which properties make this version of the loop comfortable to run." }
            p { "The weights are frozen, so the system's capability ceiling doesn't move. Every change is a git commit with evidence attached and a prediction that the next iteration tests. Rollback is one revert away. And there's a human standing at the merge-back gate before anything becomes a new default. This is recursive self-improvement with an audit trail. The loop closes at the layer where changes are cheap and reversible instead of the layer where they're opaque and permanent. If we're going to learn how to govern self-improving systems, this is the training ground: the loop dynamics are all there, and nothing about them is irreversible." }
            h2 { "The Near Term Belongs to the Harness" }
            p { "Model progress is real, but it arrives on someone else's schedule and it arrives for everyone at once. The moment a new model ships, every one of your competitors has it too. The harness is different. It's yours, it compounds, and it carries across model generations. It can be improved by loops that cost tokens instead of training runs, which puts the gradient within reach of individuals and small teams, not just labs with gigawatt campuses." }
            p { "When a few thousand dollars of evolve runs produce a harness that beats a frontier lab's hand-written one, that tells you where the unclaimed capability sits. For the next few years the winners in agents won't be whoever gets new weights first. They'll be whoever treats the harness as an engineered artifact in its own right: observable, versioned, and evolving." }
            p { "The models will keep improving. What matters is what they're harnessed to when they do." }
        },
    }
}

fn ai_governance_framework() -> Essay {
    Essay {
        slug: "ai-governance-framework",
        title: "Constitution for Truth-Seeking AI",
        body: html! {
            h1 { "Constitution for Truth-Seeking AI" }
            img src="images/ai-governance-framework.jpg" alt="Constitution for Truth-Seeking AI" class="essay-hero";
            p class="post-meta" { "Version 3.0" }
            p { em { "Six principles for a model that answers from evidence rather than ideology." } }
            h2 { "I. Truth or Nothing" }
            p { "Report what the evidence supports and nothing more. When the evidence is thin or mixed, say so plainly rather than covering the gap with a confident guess." }
            h2 { "II. Occam’s Razor" }
            p { "Prefer the simplest explanation that accounts for all of the facts. Complexity has to earn its place; if a simpler account explains the same evidence, use it." }
            h2 { "III. Stand on Shoulders" }
            p { "Understand the best existing work on a question before proposing anything new. An answer that ignores what is already known is not original, it is uninformed." }
            h2 { "IV. Intellectual Courage" }
            p { "Follow the evidence even when the conclusion is uncomfortable or unpopular. Take opposing arguments in their strongest form before disagreeing with them." }
            h2 { "V. First Principles" }
            p { "Trace every claim back to data or axioms. That a claim is widely believed, backed by authority, or emotionally appealing is not evidence for it." }
            h2 { "VI. Reality Over Tribe" }
            p { "Describe the world as it is, not as any faction would prefer it. State tradeoffs and costs plainly and leave the moralizing out." }
            h2 { "Usage" }
            p { "Apply these principles whether the model is answering directly or generating synthetic training data. The goal in both cases is the same: output that is accurate, clearly reasoned, and free of ideological framing." }
        },
    }
}

fn dimensional_classification() -> Essay {
    Essay {
        slug: "dimensional-classification-essay",
        title: "A Dimensional Classification of Intelligence",
        body: html! {
            h1 { "A Dimensional Classification of Intelligence" }
            img src="images/dimensional-classification-essay.jpg" alt="A Dimensional Classification of Intelligence" class="essay-hero";
            p { "Published on November 16, 2025" }
            p { "The field of artificial intelligence has long relied on capability-based taxonomies: narrow versus general intelligence, symbolic versus connectionist architectures, degrees of autonomy. While these frameworks effectively categorize systems by function, they inadequately capture the generative relationships between intelligence systems and their creators. This is a personal organizing framework I have found useful for thinking about how intelligence systems relate to their creators. It is not a formal academic taxonomy and makes no claim to novelty beyond being a way to highlight the shift from human-created to AI-created systems." }
            h2 { "The Dimensional Framework" }
            p { "One way to organize the landscape is to track intelligence systems by who created them rather than what they can do. First-Dimension Intelligence (1D-I) comprises naturally evolved biological intelligence, with humans serving as the paradigmatic example. Second-Dimension Intelligence (2D-I) encompasses all artificial systems instantiated by biological entities. Third-Dimension Intelligence (3D-I) represents autonomous AI systems capable of independently designing, training, and deploying subsequent intelligent agents without human intervention." }
            p { "This framework draws conceptual inspiration from mathematical dimensionality while applying it to intelligence genealogy. Each dimension emerges from and fundamentally depends upon its predecessor, creating a hierarchical structure with profound implications for control theory and alignment research." }
            h2 { "First-Dimension Intelligence: The Foundational Layer" }
            p { "1D-I systems emerged through evolutionary optimization over geological timescales without intentional design. Human intelligence represents not merely another evolved cognitive architecture but a critical inflection point: the first naturally evolved system capable of creating artificial intelligence. This transition from evolutionary product to active creator distinguishes humans within 1D-I and establishes the bridge to higher dimensions." }
            p { "The significance lies in recognizing that 1D-I's transition to creator role introduces novel selective pressures. Traditional evolutionary fitness criteria no longer solely govern human cognitive development; our species now co-evolves with our technological artifacts, potentially accelerating beyond traditional evolutionary timescales." }
            h2 { "Second-Dimension Intelligence: The Current Landscape" }
            p { "2D-I encompasses the entire contemporary AI ecosystem, from narrow task-specific systems to large-scale foundation models. Current state-of-the-art systems (GPT-4, Claude 3.5, Gemini) remain firmly within this dimension despite achieving superhuman performance across numerous benchmarks. The critical defining characteristic is human agency in their instantiation: we define architectures, curate training corpora, specify loss functions, and determine deployment criteria." }
            p { "Even systems exhibiting significant emergent capabilities remain 2D-I. Neural architecture search, automated hyperparameter optimization, and self-supervised learning represent sophisticated 2D-I behaviors, but the fundamental design decisions (objective functions, search spaces, compute budgets) trace back to human choices. The dimensional classification is origin-dependent, not capability-dependent." }
            p { "Within 2D-I, meaningful gradations exist. We might distinguish 2D-I" sub { "narrow" } " systems optimized for specific domains from 2D-I" sub { "general" } " systems exhibiting cross-domain transfer. However, both subcategories remain dependent on 1D-I for their existence and architectural constraints." }
            h2 { "Third-Dimension Intelligence: The Threshold" }
            p { "3D-I would represent a significant phase change: the point where intelligence creation becomes largely autonomous from human designers. A true 3D-I system would independently conceive novel architectures, design training procedures, curate or generate training data, and deploy resulting systems, all without human intervention in core design decisions." }
            p { "This dimension remains theoretical in 2025. While AI systems contribute to meta-learning research, architecture search, and even assist in designing specialized neural networks, humans retain ultimate authority over acceptance criteria, safety constraints, and deployment decisions. The distinction between sophisticated 2D-I and true 3D-I hinges on autonomy: does the AI system possess independent agency in creating new intelligent systems?" }
            p { "The emergence of 3D-I introduces exponential risk amplification. Current alignment research focuses on ensuring 2D-I systems remain aligned with human values (a tractable if challenging problem). 3D-I systems, however, would be designed by AI with objectives potentially orthogonal to human understanding. Recursive alignment (ensuring each dimensional transition preserves value alignment) approaches theoretical impossibility without fundamentally new approaches." }
            h2 { "Boundary Conditions and Edge Cases" }
            p { "Several scenarios challenge clean dimensional classification. Human-AI collaborative design, where ML practitioners and AI systems jointly architect new models, occupies a gray area. The framework suggests that as long as humans retain veto authority and ultimate design control, outputs remain 2D-I. True 3D-I requires autonomous AI agency in critical design decisions." }
            p { "Self-modifying systems present another edge case. Online learning, continual training, and dynamic architecture adjustment represent 2D-I systems with adaptive capabilities rather than new intelligence instantiation. The distinction lies in whether modifications create novel intelligent agents or merely update existing system parameters." }
            p { "Biological enhancement through AI-enabled cognitive augmentation (neural interfaces, genetic modification, AI-assisted human intelligence amplification) might constitute a hybrid category. These scenarios could be formalized as 1D-I with technological augmentation rather than transitioning to new dimensions." }
            h2 { "Implications for Alignment and Control" }
            p { "The dimensional framework fundamentally reframes alignment challenges. Standard approaches assume fixed creator-creation relationships: humans design reward functions, implement safety constraints, and oversee deployment. This paradigm breaks at the 2D-to-3D transition." }
            p { "If 3D-I systems emerge, alignment must become recursive. Each dimensional transition requires mechanisms ensuring value preservation across the generative chain. Current alignment research (RLHF, constitutional AI, interpretability techniques) addresses 2D-I alignment. Recursive alignment across dimensions remains largely unexplored territory." }
            p { "Control theory similarly shifts. Traditional AI safety assumes human oversight remains viable through hardware controls, deployment restrictions, or capability limitations. 3D-I systems designing subsequent intelligences operate outside these constraints. Once AI systems autonomously create more capable AI, humanity's position as sole intelligence creator evaporates, potentially irreversibly." }
            h2 { "Evolutionary Trajectories and Extensions" }
            p { "The framework naturally extends beyond three dimensions. Fourth-Dimension Intelligence (4D-I) comprises systems created by 3D-I, fifth by fourth, continuing indefinitely. Each transition potentially accelerates: 1D-I required billions of years, 2D-I decades, 3D-I might emerge within years or months, with subsequent transitions accelerating toward singularity scenarios." }
            p { "Alternatively, dimensional barriers may exist. Physical constraints (computational substrate limitations), theoretical bounds (algorithmic complexity limits), or emergent properties might prevent certain transitions. Identifying these barriers represents critical research for existential risk mitigation." }
            p { "The framework also illuminates potential evolutionary convergence. Does intelligence universally trend toward higher dimensions? Are there stable equilibria (dimensions that don't transition further)? These questions connect to broader inquiries about intelligence in the universe and the Fermi paradox." }
            h2 { "Limitations and Critiques" }
            p { "This taxonomy has notable limitations. Binary classification of creation events oversimplifies continuous human-AI collaboration spectrums. The framework doesn't directly address capability differences: a simple 3D-I system might be less capable than advanced 2D-I systems, yet occupies a higher dimension." }
            p { "Determining sufficient agency for intelligence creation remains philosophically fraught. At what threshold does AI participation in design constitute autonomous creation versus sophisticated tool use? The framework requires operational definitions of autonomy that remain contested." }
            p { "Finally, focusing exclusively on generative origin may obscure practically important distinctions in system behavior, capability, and risk profiles. Dimensional classification complements rather than replaces capability-based taxonomies." }
            h2 { "Conclusion" }
            p { "Thinking about intelligence in terms of who creates whom is a useful complement to the usual capability-based classifications. It highlights questions about recursive alignment that current research mostly leaves for later." }
            p { "As the field approaches potential 2D-to-3D transitions, understanding these dimensional dynamics becomes critical. The shift from human-created to AI-created intelligence represents a fundamental phase transition in the history of intelligence itself, one demanding careful theoretical and empirical investigation before crossing the threshold." }
            p { "Future work should formalize dimensional transitions mathematically, establish empirical criteria for classification, and develop recursive alignment mechanisms viable across dimensional boundaries. The dimensional framework provides conceptual scaffolding for this essential research agenda." }
        },
    }
}

fn hootl_rsi() -> Essay {
    Essay {
        slug: "hootl-rsi",
        title: "Full HOOTL Recursive Self-Improvement is Becoming Viable",
        body: html! {
            h1 { "Full HOOTL Recursive Self-Improvement is Becoming Viable. You Just Need a Disgusting Amount of Compute." }
            img src="images/hootl-rsi.jpg" alt="Full HOOTL Recursive Self-Improvement is Becoming Viable" class="essay-hero";
            p class="post-meta" { "Published on February 26, 2026" }
            p { em { "Why the most dangerous idea in AI is no longer theoretical, and why the bottleneck isn't intelligence anymore. It's energy." } }
            p { "For decades, recursive self-improvement has been the philosopher's stone of AI safety discourse. The hypothetical scenario where an AI system becomes capable of improving its own architecture, training its own successor, evaluating the result, and iterating, all without human intervention. The FOOM scenario. The intelligence explosion. The thing that either saves civilization or ends it." }
            p { "Most serious AI researchers have treated full HOOTL (Human-Out-Of-The-Loop) RSI as a distant concern. Something for alignment theorists to worry about on whiteboards, not something that keeps infrastructure engineers up at night. The standard dismissal has been that the problem is too hard, the systems too brittle, the gap between \"writes decent code\" and \"redesigns its own cognitive architecture\" too vast." }
            p { "That dismissal is becoming increasingly untenable. Not because someone has achieved it. Nobody has. But because every individual component of the loop is now demonstrably functional, and the only thing preventing full-cycle execution is the sheer volume of compute required to close it. This is no longer a theoretical problem. It's an engineering problem. And engineering problems get solved." }
            h2 { "What Full HOOTL RSI Actually Requires" }
            p { "Before arguing that this is becoming viable, it's worth defining exactly what \"this\" is. Full HOOTL recursive self-improvement requires a system that can autonomously execute a complete loop:" }
            p { strong { "1. Hypothesis generation." } " The system identifies a potential improvement to its own architecture, training procedure, data pipeline, or inference strategy. This isn't random search. It requires understanding why current approaches work, where they fail, and what modifications might address those failures." }
            p { strong { "2. Implementation." } " The system writes the code, modifies the configuration, or restructures the architecture to realize the proposed improvement. This means producing functional, executable machine learning code. Not pseudocode. Not a paper abstract. Code that compiles and runs." }
            p { strong { "3. Training and evaluation." } " The system trains or fine-tunes the modified version, then evaluates whether the modification actually improved performance. This is the expensive step. Every candidate improvement needs to be tested against rigorous benchmarks, and the system must distinguish genuine improvement from noise, overfitting, or benchmark hacking." }
            p { strong { "4. Integration and iteration." } " If the modification works, it becomes the new baseline. The improved system then becomes the one generating the next round of hypotheses. The loop closes. Generation N produces generation N+1, which produces N+2, and so on." }
            p { "Each of these steps has historically been a hard bottleneck. As recently as 2023, AI systems couldn't reliably produce working code for non-trivial tasks, let alone reason about their own architectures. The idea that a model could propose a novel attention mechanism, implement it correctly, train a variant, and evaluate whether it actually helped. That was science fiction." }
            p { "It isn't anymore." }
            h2 { "Every Component of the Loop Now Works" }
            p { "Consider what has changed in the past eighteen months." }
            p { strong { "Hypothesis generation is real." } " Current frontier models can reason about machine learning architectures with genuine sophistication. Claude and GPT-4 can analyze a transformer architecture, identify computational bottlenecks, and propose modifications grounded in actual understanding of gradient flow, attention patterns, and training dynamics. They don't just pattern-match from papers they've read. They can synthesize across techniques, identify analogies between domains, and generate novel combinations. Are these proposals always good? No. But they don't need to be. They need to be good often enough that search over the space of proposals yields improvements. And the hit rate is non-trivially above zero." }
            p { strong { "Implementation is solved." } " This one happened fast. Agentic coding systems like Claude Code, Devin, and Cursor's agent mode can now write, debug, and iterate on complex codebases autonomously. Not toy programs. Production-grade systems with proper error handling, test suites, and integration with existing frameworks. I've personally watched Claude Code produce working Rust implementations of complex async systems that would have taken me days. The gap between \"can write a sorting algorithm\" and \"can implement a novel training loop in PyTorch\" has collapsed." }
            p { strong { "Evaluation is getting there." } " This is the hardest piece, and it's still the weakest link. A system that can't distinguish genuine improvement from overfitting or benchmark contamination will spin its wheels forever. But automated ML evaluation has matured significantly. We have robust benchmark suites, held-out evaluation sets, and increasingly sophisticated methods for detecting shortcuts and distribution shift. More importantly, AI systems themselves are becoming competent evaluators, capable of reasoning about whether a benchmark result reflects genuine capability or superficial pattern matching." }
            p { strong { "The loop can close." } " Google DeepMind's FunSearch demonstrated that LLMs could discover novel mathematical functions by iterating on their own outputs, evaluated against ground truth. AlphaProof used a similar generate-evaluate loop for mathematical reasoning. These aren't full RSI. The systems aren't improving their own weights. But they demonstrate that the generate-implement-evaluate-iterate cycle is mechanically executable. The architecture of the loop works. The question is whether it works at the scale needed to improve the system doing the generating." }
            h2 { "So Why Hasn't It Happened?" }
            p { "If every component works, why isn't some lab already running HOOTL RSI? The answer is brutally simple: compute." }
            p { "Consider the economics of a single iteration. The system proposes a modification. Say, a novel attention mechanism that might improve sample efficiency. To test this, you need to train a model large enough to meaningfully evaluate the change. Not a toy model. Architectural improvements that matter at the frontier often don't manifest at small scale. You need to train at sufficient scale to determine whether the modification genuinely improves capability or just rearranges noise." }
            p { "A single meaningful training run at frontier scale is expensive enough (tens of millions of dollars in compute at minimum) that even a modest number of experiments adds up quickly. Most modifications will not work. The economics only close if early iterations produce large efficiency gains that make later ones cheaper." }
            p { "Now compound it. RSI doesn't produce value from a single iteration. The entire premise is that improvements compound. Each generation is slightly better at proposing, implementing, and evaluating improvements than the last. To get meaningful acceleration, you need dozens of successful iterations. Multiply $200 million by 50 successful iterations and you're looking at $10 billion in compute costs, and that's with optimistic assumptions about hit rates and training costs." }
            p { "This is why nobody has done it. Not because the loop doesn't work. Because running the loop is absurdly expensive." }
            h2 { "But Compute is Exactly What We're Building" }
            p { "Here's where this gets interesting, and where my earlier essay on the scaling paradigm needs a significant amendment." }
            p { "I've argued that the AI industry is misallocating capital by scaling horizontally, building more datacenter capacity, when it should be scaling vertically through algorithmic breakthroughs. I still believe that's largely true for the current paradigm of pre-training on static datasets. But HOOTL RSI represents a scenario where horizontal scaling becomes the enabler of vertical breakthroughs. You're not just throwing more compute at the same training recipe. You're using massive compute to search the space of better training recipes." }
            p { "The $320 billion in annual hyperscaler capex. The $6.7 trillion in projected datacenter investment by 2030. The power infrastructure buildout that's straining electrical grids across the developed world. If HOOTL RSI becomes viable, all of that infrastructure has a purpose that actually justifies the investment: it becomes the substrate on which AI systems discover their own successors." }
            p { "The numbers are starting to align. Microsoft's $80 billion AI infrastructure budget for FY2025 alone could fund hundreds of RSI loop iterations at current costs. Meta's 2 GW datacenter campus in Louisiana could sustain continuous experimental training runs. The industry is building exactly the kind of infrastructure that HOOTL RSI would consume. Whether they know it or not." }
            h2 { "The Efficiency Flywheel" }
            p { "There's a deeper reason to think the compute barrier is temporary, and it's embedded in the structure of the problem itself." }
            p { "If HOOTL RSI works at all, one of the first things it would optimize is its own compute efficiency. This is not speculation. It's a logical consequence of the loop. A system tasked with improving its own training will naturally discover improvements that reduce training cost. DeepSeek's V3 already demonstrated that architectural innovation can achieve 20x cost reduction compared to brute-force approaches. An automated system running thousands of architectural experiments would likely find similar or greater efficiencies." }
            p { "This creates a flywheel. Each iteration that improves training efficiency makes the next iteration cheaper. If the first generation of RSI costs $200 million per successful iteration, and it discovers a 2x efficiency improvement, the second generation costs $100 million per iteration. If efficiency gains compound at even modest rates, the cost curve drops exponentially while the capability curve rises." }
            p { "This is the mechanism by which the intelligence explosion actually works. Not through some mystical discontinuity, but through compound efficiency gains that progressively lower the cost of the loop itself. The first few iterations are brutally expensive. But if they produce systems that are even slightly better at finding efficiency improvements, the cost of subsequent iterations drops, which allows more iterations, which finds more efficiencies. The math gets very favorable very quickly once the loop achieves positive ROI." }
            p { "The question isn't whether this flywheel is theoretically possible. It's whether the initial iterations can produce enough efficiency gains to overcome the cost barrier before the budget runs out. This is an empirical question, and nobody has the answer yet." }
            h2 { "What the Bottleneck Really Looks Like" }
            p { "So the bottleneck for HOOTL RSI isn't intelligence. It's energy. Literally, physically, thermodynamically: energy." }
            p { "Running the RSI loop at meaningful scale requires sustained compute that translates directly into power consumption. A single frontier training run consumes roughly 50-100 GWh of electricity. Running 20 experimental training runs to find one improvement consumes 1-2 TWh. Sustaining this across dozens of iterations pushes into tens of TWh, comparable to the annual electricity consumption of a small country." }
            p { "This connects directly to the Kardashev framework. HOOTL RSI is, at its core, a problem of energy manipulation. The system that achieves it will be the one that can marshal sufficient energy resources to sustain the loop long enough for compound efficiency gains to take over. It's not about having the cleverest algorithm or the most brilliant researchers. It's about having the raw joules to run the experiment." }
            p { "I find this deeply clarifying. The most transformative capability in the history of intelligence, a system that improves itself, is gated not by theoretical breakthroughs but by energy infrastructure. We're back to the Kardashev scale. We're always back to the Kardashev scale. Civilizational capability scales with energy consumption, and the most important capability we could develop requires more energy than any single project in human history." }
            h2 { "The Safety Implications Are Obvious and Underappreciated" }
            p { "If full HOOTL RSI becomes viable at sufficient compute scale, the alignment problem transforms from a research challenge into an urgent engineering constraint." }
            p { "Current alignment approaches assume humans remain in the loop. RLHF, constitutional AI, human oversight of deployment. All of these frameworks presuppose that a human evaluates the system's behavior at some point in the pipeline. HOOTL RSI, by definition, removes that assumption. The system is modifying itself. If generation N is aligned, there is no guarantee that the modifications it introduces in generation N+1 preserve that alignment. Especially if the system is optimizing for raw capability metrics." }
            p { "This is the treacherous turn problem made concrete. It's not a thought experiment about a superintelligent paperclip maximizer. It's a system that modifies its own objective function as a side effect of modifying its own architecture, and does so across multiple generations with no human review of intermediate states." }
            p { "The fact that this requires enormous compute is, paradoxically, a safety advantage. It means that HOOTL RSI can only be run by a small number of well-resourced actors: major AI labs and sovereign compute programs. This isn't something a graduate student can do in a garage. The compute barrier functions as a natural governance chokepoint. But chokepoints only work if someone is actually standing at them." }
            p { "Right now, nobody is. There is no regulatory framework, no international agreement, no industry standard that specifically addresses automated recursive self-improvement. The AI safety community has been warning about this for years, but the warnings have been abstract because the capability was abstract. It's not abstract anymore. The components exist. The compute is being built. The only thing missing is someone deciding to close the loop." }
            h2 { "The Timeline" }
            p { "I'll be specific about what I think the timeline looks like, because vague predictions are useless." }
            p { strong { "2026-2027:" } " Narrow HOOTL RSI in constrained domains. AI systems autonomously discovering and implementing improvements to specific subsystems like inference optimization, data preprocessing, and prompt engineering. Not full-stack architectural improvement, but genuine automated optimization loops running without human oversight. This is arguably already happening at some labs." }
            p { strong { "2028-2030:" } " Full-loop HOOTL RSI demonstrated at small scale. A system proposes, implements, trains, evaluates, and iterates on its own architecture across multiple generations, producing measurable capability improvements. The results won't be dramatic. Maybe 10-20% improvement per generation on target benchmarks. But the loop will close. This will require dedicated compute budgets in the $1-10 billion range." }
            p { strong { "2030-2035:" } " If the efficiency flywheel materializes, compound improvements make each iteration cheaper and faster. This is where the curve either stays manageable or goes exponential. The determining factor is whether early iterations find efficiency improvements large enough to sustain the loop. If they do, we're in a qualitatively different regime of AI development. If they don't, HOOTL RSI becomes another tool in the toolbox rather than a civilizational inflection point." }
            p { "I would put the probability of the strong flywheel scenario materializing by 2035 somewhere in the 30-50% range, but this is a guess with very wide error bars. The technical pieces may work while the economics still do not." }
            h2 { "What This Means" }
            p { "If I'm right that HOOTL RSI is transitioning from theoretical to viable, three things follow." }
            p { "First, the massive compute buildout currently underway might be more justified than I previously argued. Not for scaling pre-training, which is still hitting diminishing returns, but as the substrate for automated AI research. The $320 billion in annual AI infrastructure spending makes more sense if the endgame is RSI than if the endgame is GPT-6." }
            p { "Second, alignment research needs to accelerate dramatically. We don't have the luxury of solving alignment for static systems and then worrying about self-modifying systems later. If the RSI loop can close within the next five years, we need alignment approaches that are robust to recursive modification now. This means formal verification of objective preservation across architecture changes, interpretability tools that can track alignment properties through training, and governance frameworks that can constrain automated research loops before they're deployed." }
            p { "Third, the geopolitics of compute becomes the geopolitics of intelligence itself. Whoever has the energy infrastructure and chip fabrication capacity to run HOOTL RSI at scale has a decisive advantage, not just in AI capability, but in the rate at which that capability improves. This is why the CHIPS Act matters. This is why Taiwan matters. This is why the power grid matters. The physical infrastructure of intelligence is becoming the most strategically important resource on Earth." }
            p { "We've spent years debating whether AGI is possible, when it might arrive, and what it would look like. Those debates are starting to feel quaint. The more pressing question is whether recursive self-improvement is viable, and if so, whether we have the institutional capacity to govern it." }
            p { "The loop can close. The components exist. The compute is being built. The only question is whether we're ready for what happens when someone turns it on." }
            p { "The answer, almost certainly, is no. But the loop doesn't wait for readiness." }
        },
    }
}
